#!/bin/sh

# Autostart
$HOME/.screenlayout/layout.sh
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &
$HOME/.config/bspwm/polybar/bar.sh
killall dunst && dunst -conf $HOME/.config/bspwm/dunst/dunstrc &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
hsetroot -fill /home/b/Pictures/gruv-forest.jpg 

# Fix pulseaudio after killing bspwm
killall pulseaudio

# Monitor configuration
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX
bspc monitor DVI-D-0 -d X

# Set mouse modifier
bspc config pointer_modifier	mod4

# Focus follows the cursor
bspc config focus_follows_pointer true

# Border width
#bspc config border_width         0

# Double border
outer='0x252525'   # outer
inner1='0x665c54'  # focused
inner2='0x504945'  # normal

trap 'bspc config border_width 0; kill -9 -$$' INT TERM

targets() {
	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .\!focused.\!fullscreen
	esac
}
bspc config border_width 12

draw() { chwb2 -I "$inner" -O "$outer" -i "3" -o "9" $*; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw $(targets focused)
		inner=$inner2 draw $(targets  normal)
	done

# Gap between windows
bspc config window_gap          15

# Focused and non-focused border colors
#bspc config normal_border_color '#504945'
#bspc config focused_border_color '#665c54'

# Split ratio
bspc config split_ratio          0.50

# Window modes
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Specific window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^1'
