#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &
$HOME/.config/bspwm/polybar/bar.sh
killall dunst && dunst -conf $HOME/.config/bspwm/dunst/dunstrc &
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
hsetroot -tile ~/Pictures/gwuv.png

# Fix pulseaudio after killing bspwm
killall pulseaudio

# Monitor configuration
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX
bspc monitor DVI-D-0 -d X

# Border width
bspc config border_width         3

# Gap between windows
bspc config window_gap          15

# Focused and non-focused border colors
bspc config normal_border_color '#504945'
bspc config focused_border_color '#665c54'

# Split ratio
bspc config split_ratio          0.50

# Window modes
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focus followe the cursor
bspc config focus_follows_pointer true

# Specific window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^1'
